#!/bin/bash


# THIS COMMAND IS LIKE THE INTERPRETER WILL GET TO KNOW WHICH SHELL ARE WE USING IT WILL DETECT THE SHELL
# IN THIS EXAMPLE WE ARE USING BASH SHELL
#

echo "hello man welcome to shell scripting part 01"

